-- Add q1..q40 as nullable TEXT columns
ALTER TABLE "DiscoveryResponse"
  ADD COLUMN "q1"  TEXT,
  ADD COLUMN "q2"  TEXT,
  ADD COLUMN "q3"  TEXT,
  ADD COLUMN "q4"  TEXT,
  ADD COLUMN "q5"  TEXT,
  ADD COLUMN "q6"  TEXT,
  ADD COLUMN "q7"  TEXT,
  ADD COLUMN "q8"  TEXT,
  ADD COLUMN "q9"  TEXT,
  ADD COLUMN "q10" TEXT,
  ADD COLUMN "q11" TEXT,
  ADD COLUMN "q12" TEXT,
  ADD COLUMN "q13" TEXT,
  ADD COLUMN "q14" TEXT,
  ADD COLUMN "q15" TEXT,
  ADD COLUMN "q16" TEXT,
  ADD COLUMN "q17" TEXT,
  ADD COLUMN "q18" TEXT,
  ADD COLUMN "q19" TEXT,
  ADD COLUMN "q20" TEXT,
  ADD COLUMN "q21" TEXT,
  ADD COLUMN "q22" TEXT,
  ADD COLUMN "q23" TEXT,
  ADD COLUMN "q24" TEXT,
  ADD COLUMN "q25" TEXT,
  ADD COLUMN "q26" TEXT,
  ADD COLUMN "q27" TEXT,
  ADD COLUMN "q28" TEXT,
  ADD COLUMN "q29" TEXT,
  ADD COLUMN "q30" TEXT,
  ADD COLUMN "q31" TEXT,
  ADD COLUMN "q32" TEXT,
  ADD COLUMN "q33" TEXT,
  ADD COLUMN "q34" TEXT,
  ADD COLUMN "q35" TEXT,
  ADD COLUMN "q36" TEXT,
  ADD COLUMN "q37" TEXT,
  ADD COLUMN "q38" TEXT,
  ADD COLUMN "q39" TEXT,
  ADD COLUMN "q40" TEXT;

-- Backfill existing rows from the JSONB blob
UPDATE "DiscoveryResponse" SET
  "q1"  = "answers"->>'q1',
  "q2"  = "answers"->>'q2',
  "q3"  = "answers"->>'q3',
  "q4"  = "answers"->>'q4',
  "q5"  = "answers"->>'q5',
  "q6"  = "answers"->>'q6',
  "q7"  = "answers"->>'q7',
  "q8"  = "answers"->>'q8',
  "q9"  = "answers"->>'q9',
  "q10" = "answers"->>'q10',
  "q11" = "answers"->>'q11',
  "q12" = "answers"->>'q12',
  "q13" = "answers"->>'q13',
  "q14" = "answers"->>'q14',
  "q15" = "answers"->>'q15',
  "q16" = "answers"->>'q16',
  "q17" = "answers"->>'q17',
  "q18" = "answers"->>'q18',
  "q19" = "answers"->>'q19',
  "q20" = "answers"->>'q20',
  "q21" = "answers"->>'q21',
  "q22" = "answers"->>'q22',
  "q23" = "answers"->>'q23',
  "q24" = "answers"->>'q24',
  "q25" = "answers"->>'q25',
  "q26" = "answers"->>'q26',
  "q27" = "answers"->>'q27',
  "q28" = "answers"->>'q28',
  "q29" = "answers"->>'q29',
  "q30" = "answers"->>'q30',
  "q31" = "answers"->>'q31',
  "q32" = "answers"->>'q32',
  "q33" = "answers"->>'q33',
  "q34" = "answers"->>'q34',
  "q35" = "answers"->>'q35',
  "q36" = "answers"->>'q36',
  "q37" = "answers"->>'q37',
  "q38" = "answers"->>'q38',
  "q39" = "answers"->>'q39',
  "q40" = "answers"->>'q40';

-- Drop the JSONB column
ALTER TABLE "DiscoveryResponse" DROP COLUMN "answers";
